### ISSUE TITLE
Indoor location sdk update interval

### ISSUE THREAD

**Issue by alexglobalbit** [proximiio/proximiio-android-demo#2]
Hi, i am using your indoor sdk, why in version proximiiolibrary:2.7.2 i am receiving locations update every 2 seconds, and in version proximiiolibrary:2.7.3 every 4 seconds?

**Comment by MikaKoskiola** [comment]
We've done extensive trials internally as well as on customer sites regarding the optimal sampling interval and for now we've ended up using 4 seconds instead of the 2. With this you will get better accuracy even though the position update interval is a bit slower. We might re-evaluate this in the future releases but for now we will stick with this.
